# Generated by Django 2.1.2 on 2018-10-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('telegram', models.CharField(blank=True, default='', max_length=50)),
                ('slack', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(choices=[('BTC/USD', 'BTC/USD')], default='BTC/USD', max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=5)),
                ('period', models.CharField(choices=[('5 minute', '5m'), ('10 minutes', '10m'), ('15 minutes', '15m'), ('30 minutes', '30m'), ('1 hour', '1h'), ('4 hours', '4h'), ('1 day', '1d')], default='5m', max_length=5)),
            ],
        ),
    ]
