# Generated by Django 2.1.2 on 2018-11-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slack',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telegram',
        ),
    ]
